### ISSUE TITLE
Running scripts

### ISSUE THREAD

**Issue by brianveltman** [MilovanovM/cake-yarn#1]
When I run a script using `Yarn.RunScript("build:Staging");` it will trigger the command as specified in package.json:
```
"scripts": {
    "build:Staging": "node_modules/.bin/cross-env NODE_ENV=staging node_modules/.bin/webpack
  },
```
But it will exit because `node_modules` is not recognized as an internal or external command.

It does work fine when using npm.

**Comment by MilovanovM** [comment]
@brianveltman thanks for using my addin! 
Could you provide the whole package.json?

**Comment by MilovanovM** [comment]
@brianveltman please provide your environment's details: OS/version, `node -v`

**Comment by MilovanovM** [comment]
Looks like it's a known issue in yarn https://github.com/yarnpkg/yarn/issues/1729
As a workaround, please try to use backslashes, so `node_modules/.bin/cross-env` should be `.\\node_modules\\.bin\\cross-env`.
Hope this will help.

**Comment by brianveltman** [comment]
Thanks will give that a shot!
