### ISSUE TITLE
Build against Cake 0.26.0 

### ISSUE THREAD

**Issue by pascalberger** [MilovanovM/cake-yarn#15]
Cake 0.26.0 introduced breaking changes. To support Cake versions >= 0.26.0 this addin needs to be built against Cake 0.26.0

**Comment by MilovanovM** [comment]
Thanks for pointing this out. I've upgraded Cake to 0.26.1 in v.0.3.7
Also I've migrated the project to NETStandard 2 (pre-release now, v.0.4.0-beta)
