### ISSUE TITLE
CakeBuild.net usage example out-of-date

### ISSUE THREAD

**Issue by dennisroche** [MilovanovM/cake-yarn#2]
The usage examples given on  [YarnRunnerAliases​.Yarn](http://cakebuild.net/api/cake.yarn/932e1214/25a98705) for running a script is out of date. 

```
Task("Yarn-Run")
    .Does(() =>
{
    Yarn.Run("hello");
});
```

should be

```
Task("Yarn-Run")
    .Does(() =>
{
    Yarn.RunScript("hello");
});
```

I couldn't see where the example was pulled from, e.g. the `README.md` so unable to submit a PR to fix.

**Comment by MilovanovM** [comment]
@dennisroche thanks for pointing this out! I've fixed the code. However, we should wait until guys from cake will update their docs site.

**Comment by MilovanovM** [comment]
It seems they've updated their docs site. Closing this issue. Thanks again!
